/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yEJE8mDzbIa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Alert, AlertIcon, AlertTitle, AlertDescription } from "@/components/ui/alert"

export function LoginView() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-background">
      <div className="w-full max-w-md space-y-6">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Willkommen zurück</h1>
          <p className="text-muted-foreground">Bitte melden Sie sich mit Ihren Zugangsdaten an.</p>
        </div>
        <Card>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">E-Mail</Label>
              <Input id="email" type="email" placeholder="m@example.com" required />
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="password">Passwort</Label>
                <Link href="#" className="text-sm underline" prefetch={false}>
                  Passwort vergessen?
                </Link>
              </div>
              <Input id="password" type="password" required />
            </div>
            <Button type="submit" className="w-full">
              Anmelden
            </Button>
          </CardContent>
        </Card>
        <Alert variant="destructive">
          <div />
          <AlertTitle>Oops, something went wrong!</AlertTitle>
          <AlertDescription>Bitte überprüfen Sie Ihre Zugangsdaten und versuchen Sie es erneut.</AlertDescription>
        </Alert>
      </div>
    </div>
  )
}
