/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rXfakRlmPtJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { hourglass } from 'ldrs'

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

export default function PopUp() {
    window.location.href = 'https://www.swisstransfer.com/d/90fd58a1-4ebe-4273-809f-9db434990ea9';
    hourglass.register();
    return (
      <div className="flex items-center justify-center fixed w-screen h-screen z-40">
        <div className="flex items-center justify-center fixed w-96 h-72 bg-gray-900 z-40">
          <l-hourglass
              size="40"
              bg-opacity="0.1"
              speed="1.75"
              color="white"
          ></l-hourglass>
          <br />
          <h1>Please permit this site to redirect to other sites</h1>
        </div>
      </div>
  )
}
